export const ADD_PRODUCT_REQUEST='ADD_PRODUCT_REQUEST'
export const ADD_PRODUCT_SUCCESS='ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_FAILURE='ADD_PRODUCT_FAILURE'


export const GET_PRODUCT_REQUEST='GET_PRODUCT_REQUEST'
export const GET_PRODUCT_SUCCESS='GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_FAILURE='GET_PRODUCT_FAILURE'

export const PATCH_PRODUCT_SUCCESS="PATCH_PRODUCT_SUCCESS"